### ISSUE TITLE
createMessage doesn't handle None message

### ISSUE THREAD

**Issue by TimoteusRuotsalainen** [lorenzofattori/M2Q#16]
Traceback (most recent call last):
  File "C:\Users\timoteus\Documents\GitHub\M2Q\m2q_midi.py", line 130, in __call__
    remoteMessage = m2q_comm.createMessage(4, channel, note, None)
  File "C:\Users\timoteus\Documents\GitHub\M2Q\m2q_comm.py", line 14, in createMessage
    if note < 0 or note > 127:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by lorenzofattori** [comment]
I'll add handling

**Comment by Quinn1210** [comment]
Greetings. I'm wondering if there is a fix for this bug. Thank you very much!

**Comment by lorenzofattori** [comment]
> Greetings. I'm wondering if there is a fix for this bug. Thank you very much!

Hi, I think this skipped my mind, but for the normal behavior it should never happen. Are you currently experiencing this? how?

Thank you
