### ISSUE TITLE
crash if no interfaces are available

### ISSUE THREAD

**Issue by lorenzofattori** [lorenzofattori/M2Q#19]
before there was a popup warning in case of no interfaces available, not it crashes

```
MidiInWinMM::initialize: no MIDI input devices currently available.

Traceback (most recent call last):
  File "c:/Users/Lorenzo/Desktop/M2Q Python/m2q_python/m2q.py", line 50, in <module>
    midiin = m2q_midi.midiSetup(settings, udpSocket, userInterface)
  File "c:\Users\Lorenzo\Desktop\M2Q Python\m2q_python\m2q_midi.py", line 221, in midiSetup
    UISetMidiPortsChoices(userInterface, ports)   
  File "c:\Users\Lorenzo\Desktop\M2Q Python\m2q_python\m2q_midi.py", line 193, in UISetMidiPortsChoices
    for port, name in enumerate(ports):
TypeError: 'NoneType' object is not iterable    
```

**Comment by TimoteusRuotsalainen** [comment]
If there are no interfaces the the m2q ui should just show an empty list of interfaces. Maybe with a text "no midi interfaces".
