### ISSUE TITLE
traceback when changing interface

### ISSUE THREAD

**Issue by lorenzofattori** [lorenzofattori/M2Q#9]
when trying to switch midi interface

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__        
    return self.func(*args)
  File "c:\Users\Lorenzo\Desktop\M2Q Python\m2q_python\m2q_ui.py", line 98, in <lambda>
    command=lambda: self.setInterface(self.interfacesValue, settings),
  File "c:\Users\Lorenzo\Desktop\M2Q Python\m2q_python\m2q_ui.py", line 326, in setInterface
    changeMidiPort(self, entryValue.current(), settings)
  File "c:\Users\Lorenzo\Desktop\M2Q Python\m2q_python\m2q_midi.py", line 185, in changeMidiPort
    userInterface.midiInterface.close_port()
AttributeError: 'NoneType' object has no attribute 'close_port'

**Comment by TimoteusRuotsalainen** [comment]
Broke here because of midi_interface vs midiInterface https://github.com/lorenzofattori/M2Q/commit/65b05e1f34dae5ceb945fdeed1e05f6e56843de8

Fixed here https://github.com/lorenzofattori/M2Q/pull/17

**Comment by lorenzofattori** [comment]
merged
